version: "3"
services:
  postgres:
    image: postgres:11
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - app
    environment:
      - POSTGRES_PASSWORD=parcom
    restart: on-failure
  pc-classroom:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - postgres
networks:
  app: