version: "3"
services:
  pc-classroom-pg:
    image: postgres:11
    ports:
      - "5432:5432"
    networks:
      - app
    environment:
      - POSTGRES_PASSWORD=parcom
    restart: on-failure
  pc-classroom:
    image: pleshakoff/pc-classroom:hw3.1
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - pc-classroom-pg
  pc-security-pg:
    image: postgres:11
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
      - app
    environment:
      - POSTGRES_PASSWORD=parcom
    restart: on-failure
  pc-security:
    image: pleshakoff/pc-security:hw3.1
    ports:
      - "8081:8081"
    networks:
      - app
    depends_on:
      - pc-security-pg
  pc-news-mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: on-failure
    networks:
      - app
  pc-news:
    image: pleshakoff/pc-news:hw3.1
    ports:
      - "8082:8082"
    networks:
      - app
    depends_on:
      - pc-news-mongo
  pc-notifier:
    image: pleshakoff/pc-notifier:hw3.1
    ports:
      - "8083:8083"
    networks:
      - app
  pc-notifier-agent-email:
    image: pleshakoff/pc-notifier-agent-email:hw3.1
    ports:
      - "8084:8084"
    networks:
      - app
  pc-notifier-agent-push:
    image: pleshakoff/pc-notifier-agent-push:hw3.1
    ports:
      - "8085:8085"
    networks:
      - app

networks:
  app: