version: "3"
services:
#################EXTERNAL######################
  pc-classroom-pg:
    image: postgres:11
    ports:
      - "5432:5432"
    networks:
      - app
    environment:
      - POSTGRES_PASSWORD=parcom
    restart: on-failure
  pc-security-pg:
    image: postgres:11
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
      - app
    environment:
      - POSTGRES_PASSWORD=parcom
    restart: on-failure
  pc-news-mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: on-failure
    networks:
      - app
  pc-user-cache-redis:
    image: redis:6.0-rc
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - app
  pc-prometheus:
    build:
      dockerfile: DockerfilePrometheus
      context: ./monitoring
    ports:
      - "9090:9090"
    networks:
      - app
  pc-grafana:
    build:
      dockerfile: DockerfileGraphana
      context: ./monitoring
    ports:
      - "3000:3000"
    depends_on:
      - pc-prometheus
    networks:
      - app
#################PARCOM######################
  pc-classroom:
    image: pleshakoff/pc-classroom:hw7
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - pc-classroom-pg
  pc-security:
    image: pleshakoff/pc-security:hw7
    ports:
      - "8081:8081"
    networks:
      - app
    depends_on:
      - pc-security-pg
  pc-news:
    image: pleshakoff/pc-news:hw7
    ports:
      - "8082:8082"
    networks:
      - app
    depends_on:
      - pc-news-mongo
  pc-notifier:
    image: pleshakoff/pc-notifier:hw7
    ports:
      - "8083:8083"
    networks:
      - app
  pc-notifier-agent-email:
    image: pleshakoff/pc-notifier-agent-email:hw7
    ports:
      - "8084:8084"
    networks:
      - app
  pc-notifier-agent-push:
    image: pleshakoff/pc-notifier-agent-push:hw7
    ports:
      - "8085:8085"
    networks:
      - app
  pc-user-cache:
    image: pleshakoff/pc-user-cache:hw7
    ports:
      - "8086:8086"
    networks:
      - app
    depends_on:
      - pc-user-cache-redis
networks:
  app: