global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'pc-classroom'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['pc-classroom:8080']