global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'pc-classroom'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['pc-classroom:8080']
  - job_name: 'pc-security'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['pc-security:8081']
  - job_name: 'pc-news'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['pc-news:8082']
  - job_name: 'pc-notifier'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['pc-notifier:8083']
  - job_name: 'pc-notifier-agent-email'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['pc-notifier-agent-email:8084']
  - job_name: 'pc-notifier-agent-push'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['pc-notifier-agent-push:8085']
  - job_name: 'pc-user-cache'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['pc-user-cache:8086']
